/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sunish;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Sunish
 */
public class DirectCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form DirectCheckOut
     */
    Connection con;
    Statement stm;
    ResultSet rs;
    Color myGreen = new Color(51, 204, 0);

    public DirectCheckOut() {
        initComponents();
        setVisible(true);
        BookIDText.requestFocus();
        JRootPane rootPane = SwingUtilities.getRootPane(CheckOutButton);
        rootPane.setDefaultButton(CheckOutButton);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int Jframewidth = this.getSize().width;
        int Jframeheight = this.getSize().height;
        int x = (dim.width - Jframewidth) / 2;
        int y = (dim.height - Jframeheight) / 2;
        setLocation(x, y);
        setSize(Jframewidth, Jframeheight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        BookIDLabel = new javax.swing.JLabel();
        BranchIDLabel = new javax.swing.JLabel();
        BookIDText = new javax.swing.JTextField();
        BranchIDText = new javax.swing.JTextField();
        CheckOutButton = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();
        HeadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management Studio");
        setMinimumSize(new java.awt.Dimension(723, 284));
        setPreferredSize(new java.awt.Dimension(795, 552));

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        RegisterButton.setText("New User");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        BookIDLabel.setText("Book ID.:");

        BranchIDLabel.setText("Branch ID.:");

        CheckOutButton.setText("Check Out");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        StatusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        StatusLabel.setForeground(new java.awt.Color(51, 204, 0));
        StatusLabel.setText("Enter a valid Card No., Book ID and Branch ID and Direct Checkout.");

        HeadingLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        HeadingLabel.setForeground(new java.awt.Color(51, 51, 255));
        HeadingLabel.setText("Check Out Books");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(HeadingLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(RegisterButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(HomeButton))
                    .add(layout.createSequentialGroup()
                        .add(BookIDLabel)
                        .add(30, 30, 30)
                        .add(BookIDText)
                        .add(39, 39, 39))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(CheckOutButton)
                            .add(layout.createSequentialGroup()
                                .add(BranchIDLabel)
                                .add(18, 18, 18)
                                .add(BranchIDText)))
                        .add(40, 40, 40)))
                .add(26, 26, 26))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(StatusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 694, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {CheckOutButton, HomeButton, RegisterButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(BranchIDText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(HomeButton)
                            .add(RegisterButton)
                            .add(HeadingLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(BookIDLabel)
                            .add(BookIDText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(BranchIDLabel)))
                .add(5, 5, 5)
                .add(CheckOutButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(StatusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new NewUser();
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Index();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        // TODO add your handling code here:
        Object a[][] = null;
        int index = 1;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "");
            stm = (Statement) con.createStatement();
            String BookId = BookIDText.getText().toString().trim();
            String BranchId = BranchIDText.getText().toString().trim();
            int flag = 0;
            String sql = "Select b.Book_id, b.title, ba.Author_name, bc.branch_id, bc.No_of_copies, bc.No_of_available from book_authors ba NATURAL JOIN book b NATURAL JOIN Book_Copies bc where ";
            if (BookId.length() > 0) {
                sql = sql + " b.book_id ='" + BookId + "' ";
                flag = 1;
            }
            if (BranchId.length() > 0) {
                if (flag == 1) {
                    sql = sql + "and ";
                }
                sql = sql + " bc.Branch_id ='" + BranchId + "' ";
                flag = 1;
            }
            if (flag == 0) {
                sql = sql + "1=2";
            }
            sql = sql + ";";
            PreparedStatement stt = con.prepareStatement(sql);
            ResultSet rs = stt.executeQuery();
            int i = 0;
            while (rs.next()) {
                i++;
            }
            a = new Object[i][6];
            stt = con.prepareStatement(sql);
            rs = stt.executeQuery();
            i = 0;
            while (rs.next()) {
                a[i][0] = rs.getObject(1);
                a[i][1] = rs.getObject(2);
                a[i][2] = rs.getObject(3);
                a[i][3] = rs.getObject(4);
                a[i][4] = rs.getObject(5);
                a[i][5] = rs.getObject(6);
                i++;
            }
        } catch (Exception err) {
            err.printStackTrace();
        } finally {
            if (stm != null) {
                try {
                    stm.close();
                } catch (SQLException sqlex) {
                    // ignore -- as we can't do anything about it here           
                }

                stm = null;
            }
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException sqlex) {
                    // ignore -- as we can't do anything about it here     
                }
                con = null;
            }
        }
        if (a.length == 0) {
            StatusLabel.setText("Please Enter a valid BookId Or Branch Number");
            StatusLabel.setForeground(Color.red);
        } else {
            dispose();
            StatusLabel.setText("Search for a new book and Check Out.");
            StatusLabel.setForeground(myGreen);
            new Checkout(a,index);
        }
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectCheckOut().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookIDLabel;
    private javax.swing.JTextField BookIDText;
    private javax.swing.JLabel BranchIDLabel;
    private javax.swing.JTextField BranchIDText;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel StatusLabel;
    // End of variables declaration//GEN-END:variables
}
