/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sunish;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sunish
 */
public class RegisterDisplay extends javax.swing.JFrame {

    /**
     * Creates new form RegisterDisplay
     */
    int CardNo;
    Connection con;
    Statement stm;
    ResultSet rs;
    Color myGreen = new Color(51, 204, 0);

    public RegisterDisplay(int LastCardNumber, String FirstName, String LastName, String Address, String Phone) {
        initComponents();
        setVisible(true);
        JRootPane rootPane = SwingUtilities.getRootPane(DoneButton);
        rootPane.setDefaultButton(DoneButton);
        CardNoText.requestFocus();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int Jframewidth = this.getSize().width;
        int Jframeheight = this.getSize().height;
        int x = (dim.width - Jframewidth) / 2;
        int y = (dim.height - Jframeheight) / 2;
        setLocation(x, y);
        setSize(Jframewidth, Jframeheight);
        CardNoText.setText(String.valueOf(LastCardNumber));
        CardNo = LastCardNumber;
        FirstNameText.setText(FirstName);
        LastNameText.setText(LastName);
        AddressText.setText(Address);
        PhoneNoText.setText(Phone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardNoLabel = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        PhoneNoLabel = new javax.swing.JLabel();
        CardNoText = new javax.swing.JTextField();
        FirstNameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        PhoneNoText = new javax.swing.JTextField();
        DoneButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();
        HeadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management Studio");
        setMinimumSize(new java.awt.Dimension(724, 400));
        setPreferredSize(new java.awt.Dimension(795, 552));

        CardNoLabel.setText("Card No.:");

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        FirstNameLabel.setText("First Name:");

        LastNameLabel.setText("Last Name:");

        AddressLabel.setText("Address");

        PhoneNoLabel.setText("Phone No.:");

        CardNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNoTextActionPerformed(evt);
            }
        });
        CardNoText.setEditable(false);

        FirstNameText.setEditable(false);

        LastNameText.setEditable(false);

        AddressText.setEditable(false);

        PhoneNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoTextActionPerformed(evt);
            }
        });
        PhoneNoText.setEditable(false);

        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        StatusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        StatusLabel.setForeground(new java.awt.Color(51, 204, 0));
        StatusLabel.setText("Provide user with his new Card no. Recheck his details and confirm his registration.");

        HeadingLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        HeadingLabel.setForeground(new java.awt.Color(51, 51, 255));
        HeadingLabel.setText("Confirm Details");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(EditButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(DoneButton))
                    .add(layout.createSequentialGroup()
                        .add(45, 45, 45)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(LastNameLabel)
                                    .add(AddressLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(AddressText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                                    .add(LastNameText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                                .add(2, 2, 2))
                            .add(layout.createSequentialGroup()
                                .add(FirstNameLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(FirstNameText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(PhoneNoLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(PhoneNoText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(20, 20, 20)
                                .add(CardNoLabel)
                                .add(18, 18, 18)
                                .add(CardNoText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(HeadingLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(HomeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(45, 45, 45))
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(StatusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 686, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {DoneButton, EditButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(HomeButton)
                    .add(HeadingLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CardNoLabel)
                    .add(CardNoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(FirstNameLabel)
                    .add(FirstNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LastNameLabel)
                    .add(LastNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AddressLabel)
                    .add(AddressText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PhoneNoLabel)
                    .add(PhoneNoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DoneButton)
                    .add(EditButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 34, Short.MAX_VALUE)
                .add(StatusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoTextActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Index();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        String FirstName = FirstNameText.getText();
        String LastName = LastNameText.getText();
        String Address = AddressText.getText();
        String Phone = PhoneNoText.getText();
        int flag = 0;
        if (FirstName.length() == 0) {
            StatusLabel.setText("First Name cannot be blank");
            StatusLabel.setForeground(Color.red);
        } else if (LastName.length() == 0) {
            StatusLabel.setText("Last Name cannot be blank");
            StatusLabel.setForeground(Color.red);
        } else if (Address.length() == 0) {
            StatusLabel.setText("Address cannot be blank");
            StatusLabel.setForeground(Color.red);
        } else if (Phone.length() == 0) {
            StatusLabel.setText("Phone cannot be blank");
            StatusLabel.setForeground(Color.red);
        } else {
            String sql = "INSERT INTO Borrower values(" + CardNo + ",'" + FirstName + "','" + LastName + "','" + Address + "','" + Phone + "');";
            String sql2 = "Select card_no from Borrower where Fname = '" + FirstName + "' and Lname = '" + LastName + "' and Address = '" + Address + "' ";

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "");
                stm = (Statement) con.createStatement();
                PreparedStatement stt = con.prepareStatement(sql2);
                ResultSet rs = stt.executeQuery();
                while (rs.next()) {
                    JOptionPane.showMessageDialog(null, "A user with a same Name exist whose Card Number is - " + rs.getObject(1), "Information", 1);
                    flag = 1;
                }
                if (flag == 0) {
                    stt = con.prepareStatement(sql);
                    stt.executeUpdate();
                    System.out.println(sql);
                    dispose();
                    new Index();
                } else {
                    StatusLabel.setText("Provide the user with the existing Card Number or Edit Name");
                    StatusLabel.setForeground(Color.red);
                }
            } catch (Exception err) {
                err.printStackTrace();
            } finally {
                if (stm != null) {
                    try {
                        stm.close();
                    } catch (SQLException sqlex) {
                        // ignore -- as we can't do anything about it here           
                    }

                    stm = null;
                }
                if (con != null) {
                    try {
                        con.close();
                    } catch (SQLException sqlex) {
                        // ignore -- as we can't do anything about it here     
                    }
                    con = null;
                }
            }
        }

    }//GEN-LAST:event_DoneButtonActionPerformed

    private void CardNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNoTextActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        CardNoText.setEditable(false);
        FirstNameText.setEditable(true);
        LastNameText.setEditable(true);
        AddressText.setEditable(true);
        PhoneNoText.setEditable(true);
        FirstNameText.requestFocus();

    }//GEN-LAST:event_EditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegisterDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel CardNoLabel;
    private javax.swing.JTextField CardNoText;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JLabel PhoneNoLabel;
    private javax.swing.JTextField PhoneNoText;
    private javax.swing.JLabel StatusLabel;
    // End of variables declaration//GEN-END:variables
}
